/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author Alumno Tarde
 */
public class TarificadorTest extends javax.swing.JFrame {

    /**
     * Creates new form TarificadorTest
     */
    public TarificadorTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelPrecio = new javax.swing.JLabel();
        botonCalcular = new javax.swing.JButton();
        labelPeso = new javax.swing.JLabel();
        textPeso = new javax.swing.JTextField();
        labelDestino = new javax.swing.JLabel();
        comboDestino = new javax.swing.JComboBox<>();
        labelTipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        labelModalidad = new javax.swing.JLabel();
        comboModalidad = new javax.swing.JComboBox<>();
        labelValorDeclarado = new javax.swing.JLabel();
        textValorDeclarado = new javax.swing.JTextField();
        checkAcuse = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPrecio.setText("Precio: ");

        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        labelPeso.setText("Peso");

        labelDestino.setText("Destino");

        comboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional" }));

        labelTipo.setText("Tipo");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carta", "Tarjeta Postal" }));

        labelModalidad.setText("Modalidad");

        comboModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordinaria", "Certificada", "Urgente", "Urgente y Certificada" }));
        comboModalidad.setMinimumSize(new java.awt.Dimension(92, 20));
        comboModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModalidadActionPerformed(evt);
            }
        });

        labelValorDeclarado.setText("Valor Declarado");

        checkAcuse.setText("Acuse de recibo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelModalidad)
                                        .addComponent(labelPeso))
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textPeso)
                                        .addComponent(comboModalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelValorDeclarado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textValorDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(checkAcuse, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDestino)
                    .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModalidad)
                    .addComponent(comboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textValorDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorDeclarado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAcuse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecio)
                .addContainerGap())
        );

        jSeparator1.setVisible(false);
        labelValorDeclarado.setVisible(false);
        textValorDeclarado.setVisible(false);
        checkAcuse.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModalidadActionPerformed
        // TODO add your handling code here:
        int modalidad = comboModalidad.getSelectedIndex();
        boolean certificado = false;
        
        if (modalidad == 1 || modalidad == 3) {
            certificado = true;
            labelValorDeclarado.setVisible(true);
            textValorDeclarado.setVisible(true);
            checkAcuse.setVisible(true);
            jSeparator1.setVisible(true);
        } else {
            certificado = false;
            labelValorDeclarado.setVisible(false);
            textValorDeclarado.setVisible(false);
            checkAcuse.setVisible(false);
            jSeparator1.setVisible(false);
        }
    }//GEN-LAST:event_comboModalidadActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        double valor = 0;
        double declaracion = 0;
        
        double peso = Integer.parseInt(textPeso.getText());
        int counter = 0;
        int modalidad = comboModalidad.getSelectedIndex();
        boolean certificado = false;
        boolean pesado = false;
        if (modalidad == 0) {
            if (peso > 0 && peso <= 20) {
                    valor = 0.70;
                } else if (peso >20 && peso <= 50) {
                    valor = 0.80;
                } else if (peso > 50 && peso <= 100) {
                    valor = 1.25;
                } else if (peso > 100 && peso <= 500) {
                    valor = 2.50;
                } else if (peso > 500 && peso <= 1000) {
                    valor = 5.15;
                } else if (peso > 1000 && peso <= 2000) {
                    valor = 5.60;
                } else {
                    pesado = true;
                }
        } else if (modalidad == 1) {
            certificado = true;
            if (peso > 0 && peso <= 20) {
                    valor = 4.15;
                } else if (peso >20 && peso <= 50) {
                    valor = 4.25;
                } else if (peso > 50 && peso <= 100) {
                    valor = 4.70;
                } else if (peso > 100 && peso <= 500) {
                    valor = 5.95;
                } else if (peso > 500 && peso <= 1000) {
                    valor = 8.60;
                } else if (peso > 1000 && peso <= 2000) {
                    valor = 9.05;
                }else {
                    pesado = true;
                }
        } else if (modalidad == 2) {
            if (peso > 0 && peso <= 20) {
                    valor = 4.10;
                } else if (peso >20 && peso <= 50) {
                    valor = 3.22;
                } else if (peso > 50 && peso <= 100) {
                    valor = 4.74;
                } else if (peso > 100 && peso <= 500) {
                    valor = 6.38;
                }else {
                    pesado = true;
                }
        } else if (modalidad ==3) {
            certificado = true;
            if (peso > 0 && peso <= 20) {
                    valor = 8.28;
                } else if (peso >20 && peso <= 50) {
                    valor = 8.40;
                } else if (peso > 50 && peso <= 100) {
                    valor = 8.92;
                } else if (peso > 100 && peso <= 500) {
                    valor = 10.55;
                } else if (peso > 500 && peso <= 1000) {
                    valor = 14.00;
                } else if (peso > 1000 && peso <= 2000) {
                    valor = 14.58;
                }else {
                    pesado = true;
                }
        }
       if (textValorDeclarado.isVisible()) {
           int valorDeclarado = Integer.parseInt(textValorDeclarado.getText());
           if (valorDeclarado >= 50) {
        while(valorDeclarado >= 50) {
            valorDeclarado = valorDeclarado - 50;
            counter = counter + 1;
            }
            declaracion = counter * 2.10;
           }
            
            if (checkAcuse.isSelected()) {
                valor = valor + declaracion + 1.94;
            } else {
                valor = valor + declaracion;
            }
        
       }
       
       if (pesado){
           labelPrecio.setText("DEMASIADO PESADO");
       } else {
           labelPrecio.setText("Precio: "+String.valueOf(valor)+" €");
       }
       
    }//GEN-LAST:event_botonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarificadorTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarificadorTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarificadorTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarificadorTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarificadorTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JCheckBox checkAcuse;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.JComboBox<String> comboModalidad;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelModalidad;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelValorDeclarado;
    private javax.swing.JTextField textPeso;
    private javax.swing.JTextField textValorDeclarado;
    // End of variables declaration//GEN-END:variables
}
